name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Configure CMake
      run: cmake -H. -B_build -DBUILD_TESTS=OFF

    - name: Build
      run: cmake --build _build

    - name: Test demo
      run: |
        export LOG_PATH=./log.txt
        echo "Hello CI" | ./_build/demo
        cat log.txt

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t logger .
    
    - name: Test Docker container
      run: |
        mkdir logs
        echo "Hello from Docker CI" | docker run -i -v $(pwd)/logs:/home/logs/ logger
        cat logs/log.txt
